# Generated by Django 5.0.7 on 2024-07-23 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DriverInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=15)),
                ('vehicle_number', models.CharField(max_length=15)),
                ('number_of_parcels', models.IntegerField()),
                ('notes', models.TextField()),
                ('signatures', models.TextField()),
            ],
        ),
    ]
