# Generated by Django 5.0.7 on 2024-07-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driverinfo',
            name='contact_number',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_number',
            field=models.CharField(max_length=20),
        ),
    ]
