# Generated by Django 5.0.7 on 2024-07-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formapp', '0002_alter_driverinfo_contact_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('contact_number', models.CharField(max_length=20)),
                ('vehicle_number', models.CharField(max_length=20)),
                ('number_of_parcels', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('signatures', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='contact_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='signatures',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driverinfo',
            name='vehicle_number',
            field=models.CharField(max_length=100),
        ),
    ]
